# Site settings
email: Zhendi.huang@hotmail.com
baseurl: "/MyWeb"
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: Zhendi
description:
url: ""
twitter_username:
default_img:

# Profile settings
name: Zhendi
profile_img: /img/pf.jpg
profile: Zhendi Huang is ...
social:
  github: https://github.com/GrietjeWong

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
